development:
  forest_env_secret: ec560eac42f2e8ed9e33455362cf0c2b7ea6770ef850d035ce6f876550564c1a
  forest_auth_secret: HMkV-XCJkzVkj4_HkGn_Mw
staging:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
